### PR TITLE
Fixed TypeError: "Illegal offset type"

### LINKED ISSUE #15: TypeError: "Illegal offset type"
```php
TypeError: "Illegal offset type" (EXCEPTION) in "plugins/MaxEnchants.phar/src/Xenophilicy/MaxEnchants/MaxEnchants" at line 201

### PR DESCRIPTION
**Pull request by JavierLeon9966**
Fixes #15

### CODE REVIEW

File: src/Xenophilicy/MaxEnchants/MaxEnchants.php [hunk 1]
```diff
@@ -174,6 +175,8 @@ private function enchantItem(CommandSender $sender, array $args): void{
             $sender->sendMessage(TF::RED . "There is no such enchantment with ID " . TF::YELLOW . $args[1]);
             return;
         }
+        $enchantmnetName = $enchantment->getName();
```
Comment (Xenophilicy) [inline src/Xenophilicy/MaxEnchants/MaxEnchants.php]: This is a typo. Change `$enchantmnetName` to `$enchantmentName`.

**Review by Xenophilicy — CHANGES_REQUESTED** [review]
Along with the typo, you missed an occurrence of `$enchantment->getName()` on [line 82](https://github.com/Xenophilicy/MaxEnchants/blob/master/src/Xenophilicy/MaxEnchants/MaxEnchants.php#L82). Please fix these two problems and include a patch-level version bump in `plugin.yml`, then I will merge.

**Comment by JavierLeon9966** [comment]
Done
